###########
# site.title

title:    'ArchitectSteve'
subtitle: 'Replicating 2D images into 3D structures in Minecraft'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
